package com.fatec.livrariaecommerce.models.domain;

public enum StatusVenda {
    EM_PROCESSAMENTO,
    PAGAMENTO_REALIZADO,
    ENVIADO_PARA_TRANSPORTADORA,
    EM_TRANSPORTE,
    ENTREGUE,
    TROCA_SOLICITADA,
    TROCA_RECUSADA,
    TROCA_ACEITA,
    PRODUTO_ENVIADO_PARA_TROCA,
    PRODUTO_RECEBIDO_PARA_TROCA,
    TROCA_CANCELAMENTO_REALIZADO;
}
